### ISSUE TITLE
VoxelSniper Build 382 Fails to load

### ISSUE THREAD

**Issue by imasonaz** [TVPT/VoxelSniper#264]
Running Spigot 1.8.7, VoxelSniper Build 382 fails to load with (first line at bottom, sorry!):
```
10.06 10:18:24 [Server] INFO ... 14 more
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.api.expansion.Expansion
10.06 10:18:24 [Server] INFO ... 14 more
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_72]
10.06 10:18:24 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/api/expansion/Expansion
10.06 10:18:24 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
10.06 10:18:24 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:534) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:740) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot.jar:git-Spigot-07a5b1b-53433de]
10.06 10:18:24 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/api/expansion/Expansion
10.06 10:18:24 [Server] ERROR Could not load 'plugins/VoxelSniper-7.0.0-SNAPSHOT.jar' in folder 'plugins'
```

**Comment by Deamon5550** [comment]
You are:
A) running the wronge jar, the one you would want is [VoxelSniper-7.0.0-SNAPSHOT-all.jar](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/) however,
B) You are also running the unstable 7.0.0 builds which are not yet fully funtioning

The jar you are probably looking for is [VoxelSniper-5.170.0-SNAPSHOT.jar](http://dev.bukkit.org/media/files/796/868/VoxelSniper-5.170.0-SNAPSHOT.jar)
