### ISSUE TITLE
[Forge] Crash report

### ISSUE THREAD

**Issue by loganspeck** [TVPT/VoxelSniper#266]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1446-2.1DEV-500.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/6/15 3:28 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.sponge.VoxelSniperSponge
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.sponge.VoxelSniperSponge
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/expansion/Expansion
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.expansion.Expansion
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 244912464 bytes (233 MB) / 907018240 bytes (865 MB) up to 3806855168 bytes (3630 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1487-universal.jar) 
	UC	Forge{11.14.3.1487} [Minecraft Forge] (forge-1.8-11.14.3.1487-universal.jar) 
	UC	Sponge{1.8-1446-2.1DEV-500} [SpongePowered Sponge] (minecraft.jar) 
	UC	EC{1.4} [ExtraChat] (ExtraChat-1.4e.jar) 
	UC	dotdash-linkclicker{1.0.1} [LinkClicker] (LinkClicker.jar) 
	UC	permissionsex{2.0-SNAPSHOT} [PermissionsEx] (permissionsex-2.0-SNAPSHOT.jar) 
	UC	pik{mk1} [Pik] (pik-mk1.jar) 
	UE	voxelsniperforge{7.0.0} [VoxelSniper-Forge] (VoxelSniper-7.1.0-SNAPSHOT.jar) 
	UE	voxelsnipersponge{7.0.0} [VoxelSniper-Sponge] (VoxelSniper-7.1.0-SNAPSHOT.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1446-2.1DEV-500.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Deamon5550** [comment]
What build and jar are you using?

**Comment by loganspeck** [comment]
Oh sorry I thought it was in the dump.

VoxelSniper-7.1.0-SNAPSHOT.jar BUILD-390

**Comment by Deamon5550** [comment]
Ah, you're using the wrong jar, you need the one with the shaded dependencies [VoxelSniper-7.1.0-SNAPSHOT-all.jar](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/lastSuccessfulBuild/artifact/build/libs/VoxelSniper-7.1.0-SNAPSHOT-all.jar)

**Comment by loganspeck** [comment]
Oh thank you very much!
