### ISSUE TITLE
[Forge/Sponge] NPE onPlayerJoin

### ISSUE THREAD

**Issue by loganspeck** [TVPT/VoxelSniper#267]
```
[Server thread/ERROR] [voxelsnipersponge/]: Error setting up default player settings.
java.lang.NullPointerException
	at com.voxelplugineering.voxelsniper.entity.AbstractPlayer.resetSettings(AbstractPlayer.java:195) ~[AbstractPlayer.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.entity.AbstractPlayer.init(AbstractPlayer.java:113) [AbstractPlayer.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.sponge.SpongeServiceProvider$PlayerRegistryProvider.get(SpongeServiceProvider.java:257) [SpongeServiceProvider$PlayerRegistryProvider.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.registry.ProvidedWeakRegistry.get(ProvidedWeakRegistry.java:65) [ProvidedWeakRegistry.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.service.PlayerRegistryService.getPlayer(PlayerRegistryService.java:86) [PlayerRegistryService.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.sponge.event.handler.SpongeEventHandler.onPlayerJoin(SpongeEventHandler.java:90) [SpongeEventHandler.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.common.event.handler.PlayerJoinEventHandler_SpongeEventHandler_onPlayerJoin31.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredHandler.handle(RegisteredHandler.java:86) [RegisteredHandler.class:1.8-1446-2.1DEV-500+unknown-b500.git-unknown]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:248) [SpongeEventManager.class:1.8-1446-2.1DEV-500+unknown-b500.git-unknown]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:259) [SpongeEventManager.class:1.8-1446-2.1DEV-500+unknown-b500.git-unknown]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:216) [sn.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:234) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:50) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:186) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:248) [gr.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:191) [rc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:727) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
```

**Comment by loganspeck** [comment]
`VoxelSniper-7.1.0-SNAPSHOT-all.jar BUILD-390`

**Comment by Deamon5550** [comment]
make sure you are running the absolute latest version of sponge, I think you're missing the changes in [this commit](https://github.com/SpongePowered/SpongeCommon/commit/a54ccacee333283dc1579598812ded138980a8a5).

**Comment by loganspeck** [comment]
I just upgraded to `forge 1487` and `sponge 516` and the error went away.
