### ISSUE TITLE
NullPointerException using the command: "/b b m"

### ISSUE THREAD

**Issue by UNC00KED** [TVPT/VoxelSniper#277]
Person on my build team is getting an internal error when running the command */b b m*. It's weird because I have yet to run into an issue at all using VoxelSniper.

Here is the stack trace
```java
02.11 22:31:52 [Server] INFO ... 14 more
02.11 22:31:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at com.thevoxelbox.voxelsniper.VoxelSniper.onCommand(VoxelSniper.java:138) ~[?:?]
02.11 22:31:52 [Server] INFO at com.thevoxelbox.voxelsniper.VoxelSniperListener.onCommand(VoxelSniperListener.java:76) ~[?:?]
02.11 22:31:52 [Server] INFO at com.thevoxelbox.voxelsniper.command.VoxelBrushCommand.onCommand(VoxelBrushCommand.java:77) ~[?:?]
02.11 22:31:52 [Server] INFO Caused by: java.lang.NullPointerException
02.11 22:31:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
02.11 22:31:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT42-1.8.jar:git-Spigot-550ebac-7019900]
02.11 22:31:52 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'b' in plugin VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1
02.11 22:31:52 [Server] ERROR null
02.11 22:31:52 [Server] INFO jaredalsup1234 issued server command: /b b m
```

**Comment by Gnat008** [comment]
I am also seeing this.
Spigot 1.8.8
VoxelSniper 7.1.0 build # 418

`[18:29:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'b' in com.voxelplugineering.voxelsniper.bukkit.service.command.BukkitCommand(b)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
        at com.voxelplugineering.voxelsniper.commands.BrushCommand.execute(BrushCommand.java:74) ~[?:?]
        at com.voxelplugineering.voxelsniper.bukkit.service.command.BukkitCommand.execute(BukkitCommand.java:78) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        ... 14 more
`

**Comment by Deamon5550** [comment]
Versions targetting bukkit are no longer supported.
