### ISSUE TITLE
Forge/Sponge InvocationTargetException

### ISSUE THREAD

**Issue by lastlich** [TVPT/VoxelSniper#278]
I have installed VoxelSniper into a server with Sponge build 833 and the server spits errors in console (the server does not stop however). I have forge 11.14.4.1572 and running Java 8
The error report:
https://gist.github.com/lastlich/b1531181d7da1f69a160#file-voxelsnipercrash-txt

also whenever player logs in error appears :
```
[14:28:33] [Server thread/ERROR] [Sponge/]: Could not pass PlayerLoggedInEvent to SpongePlugin:VoxelSniper-Sponge{7.1.0}
java.lang.IllegalArgumentException: GlobalAliasHandler service was not found in the current context.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.jar:?]
	at com.voxelplugineering.voxelsniper.util.Context.getRequired(Context.java:91) ~[Context.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.entity.AbstractPlayer.<init>(AbstractPlayer.java:103) ~[AbstractPlayer.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.sponge.entity.SpongePlayer.<init>(SpongePlayer.java:63) ~[SpongePlayer.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.sponge.SpongeServiceProvider$PlayerRegistryProvider.get(SpongeServiceProvider.java:291) ~[SpongeServiceProvider$PlayerRegistryProvider.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.registry.ProvidedWeakRegistry.get(ProvidedWeakRegistry.java:66) ~[ProvidedWeakRegistry.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.service.PlayerRegistryService.getPlayer(PlayerRegistryService.java:87) ~[PlayerRegistryService.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at com.voxelplugineering.voxelsniper.sponge.event.handler.SpongeEventHandler.onPlayerJoin(SpongeEventHandler.java:80) ~[SpongeEventHandler.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.common.event.listener.JoinListener_SpongeEventHandler_onPlayerJoin17.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:92) ~[RegisteredListener.class:1.8-1568-2.1-DEV-833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:225) [SpongeModEventManager.class:1.8-1568-2.1-DEV-833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:186) [SpongeModEventManager.class:1.8-1568-2.1-DEV-833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:265) [SpongeModEventManager.class:1.8-1568-2.1-DEV-833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:237) [SpongeModEventManager.class:1.8-1568-2.1-DEV-833]
	at org.spongepowered.common.Sponge.postEvent(Sponge.java:104) [Sponge.class:1.8-1568-2.1-DEV-833]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:285) [sn.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:236) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:51) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:187) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:248) [gr.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:191) [rc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:727) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
```

Thank you

**Comment by Deamon5550** [comment]
There have been many breaking changes in sponge over the last 300 or so builds between the one I last tested on and the one you're running so I'm a bit surprised that it runs at all. I'll update for latest sponge soon, and if that wasn't whats causing this then I'll look into that too.

**Comment by Deamon5550** [comment]
No longer an issue in the [latest release for sponge 1.10.2](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/)
