### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by moose51789** [TVPT/VoxelSniper#280]
Voxelsniper 7 build 418 Spigot 1.8.8 latest build (git-spigot-db6de12-07c3001)

Plugin is unable to load and has been the case for a bit now, i'm not sure if i'm missing some other plugin or util thats needed to allow it to run but i didn't see a bug report so i figured i'd make one.

Relevant log:
```
[19:00:26] [Server thread/ERROR]: Could not load 'plugins/VoxelSniper-7.1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/service/logging/Logger
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/service/logging/Logger
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.service.logging.Logger
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	... 6 more
```

**Comment by Deamon5550** [comment]
Wrong jar file, you need [VoxelSniper-7.1.0-SNAPSHOT-all.jar](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/lastSuccessfulBuild/artifact/build/libs/VoxelSniper-7.1.0-SNAPSHOT-all.jar).
