### ISSUE TITLE
Doesn't work on java 7

### ISSUE THREAD

**Issue by buhiroshi0205** [TVPT/VoxelSniper#284]
It wouldn't load on spigot running on a server with java 1.7. I don't know if it is supposed to be like this, but I'm reporting this anyway.

Detailed error log:
[22:22:57] [Server thread/ERROR]: Could not load 'plugins\VoxelSniper-7.1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/voxelplugineering/voxelsniper/bukkit/VoxelSniperBukkit : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:740) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
Caused by: java.lang.UnsupportedClassVersionError: com/voxelplugineering/voxelsniper/bukkit/VoxelSniperBukkit : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
	... 14 more

**Comment by gabizou** [comment]
VoxelSniper requires Java 8.

**Comment by buhiroshi0205** [comment]
OK thank you.
