### ISSUE TITLE
issue from voxelsniper when using endercore 1.8.9

### ISSUE THREAD

**Issue by scootashy** [TVPT/VoxelSniper#288]
if i put endercore in server stops and tries to restart found this in logs

[09:45:59] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[09:45:59] [Server thread/ERROR] [FML/]: Caught exception from voxelsniperforge
java.lang.IllegalStateException: Attempted to register service providers while manager was running.
    at com.voxelplugineering.voxelsniper.ServiceManager.register(ServiceManager.java:248) ~[ServiceManager.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
    at com.voxelplugineering.voxelsniper.forge.VoxelSniperForge.serverPreStart(VoxelSniperForge.java:110) ~[VoxelSniperForge.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[pony.jar:?]
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857) [Loader.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:252) [ko.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[09:45:59] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.IllegalStateException: Attempted to register service providers while manager was running.
    at com.voxelplugineering.voxelsniper.ServiceManager.register(ServiceManager.java:248) ~[ServiceManager.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
    at com.voxelplugineering.voxelsniper.forge.VoxelSniperForge.serverPreStart(VoxelSniperForge.java:110) ~[VoxelSniperForge.class:7.1.0-SNAPSHOT+unknown-b0.git-unknown]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[pony.jar:?]
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.8.9.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.8.9.jar:?]
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857) [Loader.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:252) [ko.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[09:45:59] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.

**Comment by Deamon5550** [comment]
Forge version is no longer supported use the [latest release for sponge](http://ci.voxelmodpack.com/view/VoxelSniper/job/VoxelSniper/).
