### ISSUE TITLE
NoClassDefFound Logger

### ISSUE THREAD

**Issue by seema84** [TVPT/VoxelSniper#289]
Build 422

Could not load 'plugins\VoxelSniper-7.1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/voxelplugineerin/voxelsniper/service/logging/Logger
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.9.2.jar:gi
t-Spigot-ccb6016-f92e01b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.2.jar:git-
Spigot-ccb6016-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:743) [spigot-1.9.2.jar:git-Spigo
t-ccb6016-f92e01b]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot-1.9.2.jar:git-Spigot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spig
ot-ccb6016-f92e01b]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Sp
igot-ccb6016-f92e01b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/voxelplugineering/voxelsniper/service/logging/Logger
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.2.jar:git-S
pigot-ccb6016-f92e01b]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.2.jar:gi
t-Spigot-ccb6016-f92e01b]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: com.voxelplugineering.voxelsniper.service.logging.Logger
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.2.jar:g
it-Spigot-ccb6016-f92e01b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.2.jar:gi
t-Spigot-ccb6016-f92e01b]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.2.jar:git-S
pigot-ccb6016-f92e01b]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.2.jar:gi
t-Spigot-ccb6016-f92e01b]
        ... 14 more

**Comment by Deamon5550** [comment]
Wrong jar file, use VoxelSniper-7.1.0-SNAPSHOT-all.jar or for spigot the more recommended [5.171](http://dev.bukkit.org/media/files/912/511/VoxelSniper-5.171.0-SNAPSHOT.jar)

**Comment by seema84** [comment]
oh right .. i overlooked the filesize
