### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by PeterkalM** [TVPT/VoxelSniper#307]
When I run the server, this error shows up:
```
[20:14:22 ERROR] [voxelsniper]: Failed to save default configuration
[20:14:22 ERROR] [STDERR]: java.nio.file.NoSuchFileException: /home/minecraft/servers/ehitus/config/voxelsniper/1488564862276voxelsniper.conf.tmp
[20:14:22 ERROR] [STDERR]:      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[20:14:22 ERROR] [STDERR]:      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[20:14:22 ERROR] [STDERR]:      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[20:14:22 ERROR] [STDERR]:      at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[20:14:22 ERROR] [STDERR]:      at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[20:14:22 ERROR] [STDERR]:      at java.nio.file.Files.newOutputStream(Files.java:216)
[20:14:22 ERROR] [STDERR]:      at java.nio.file.Files.newBufferedWriter(Files.java:2860)
[20:14:22 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.createAtomicBufferedWriter(AtomicFiles.java:55)
[20:14:22 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.lambda$createAtomicWriterFactory$0(AtomicFiles.java:38)
[20:14:22 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:184)
[20:14:22 ERROR] [STDERR]:      at com.thevoxelbox.voxelsniper.VoxelSniperConfiguration.init(VoxelSniperConfiguration.java:119)
[20:14:22 ERROR] [STDERR]:      at com.thevoxelbox.voxelsniper.VoxelSniper.onInit(VoxelSniper.java:146)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameInitializationEventListener_VoxelSniper_onInit12.handle(Unknown Source)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:324)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:200)
[20:14:22 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:204)
[20:14:22 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zod000(SourceFile:1233)
[20:14:22 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:185)
[20:14:22 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:428)
[20:14:22 ERROR] [STDERR]:      at java.lang.Thread.run(Thread.java:745)
```

I just want do know is this normal thing, and I can just ignore it? VoxelSniper works otherwise.

**Comment by Deamon5550** [comment]
Do you not have write permissions to the config folder or something? It'll still work fine its just failing to create the configuration file so you won't be able to configure anything.

**Comment by PeterkalM** [comment]
Yes, i have. `drwxr-xr-x 5 minecraft nogroup 4096 Feb 26 14:19 config`
In the config folder isn't even voxelsniper folder.

**Comment by Deamon5550** [comment]
Well if it's consistently happening then I'd say its a bug with configurate, or your disk is full, or you don't actually have permissions to create files there. Definitely not a bug with sniper though as we leave all the actual saving to configurate.
