### ISSUE TITLE
VoxelSniper v5.171.0 exception

### ISSUE THREAD

**Issue by Sandukhan** [TVPT/VoxelSniper#309]
Tends to spam the console from time to time. Runing latest VoxelSniper v5.171.0 on spigot 1.11.2-R0.1 (4741400-c1aa859)

[13:32:26] [Craft Scheduler Thread - 6/WARN]: [VoxelSniper] Plugin VoxelSniper v5.171.0-SNAPSHOT generated an exception while executing task 19
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.mcstats.Metrics.postPlugin(Metrics.java:357) ~[?:?]
	at org.mcstats.Metrics.access$4(Metrics.java:350) ~[?:?]
	at org.mcstats.Metrics$1.run(Metrics.java:245) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-4741400-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_server.jar:git-Spigot-4741400-c1aa859]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by masterX244** [comment]
use the setting for disable plugin metrics, afaik it resides in a separate folder

**Comment by Deamon5550** [comment]
Something else is pulling in an older version of Metrics, the version of VoxelSniper you are running has the updated version.
