### ISSUE TITLE
Failed to save default config

### ISSUE THREAD

**Issue by seema84** [TVPT/VoxelSniper#310]
Sponge Vanilla Build 231 (1.11.2)

`[17:31:39 ERROR] [voxelsniper]: Failed to save default configuration
[17:31:39 ERROR] [STDERR]: java.nio.file.NoSuchFileException: path\Spongebeta\config\voxelsn
iper\1489422699786voxelsniper.conf.tmp
[17:31:39 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at java.nio.file.Files.newOutputStream(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at java.nio.file.Files.newBufferedWriter(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.createAtomicBufferedWriter(Ato
micFiles.java:55)
[17:31:39 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles.lambda$createAtomicWriterFacto
ry$0(AtomicFiles.java:38)
[17:31:39 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractC
onfigurationLoader.java:184)
[17:31:39 ERROR] [STDERR]:      at com.thevoxelbox.voxelsniper.VoxelSniperConfiguration.init(VoxelSniperConfig
uration.java:119)
[17:31:39 ERROR] [STDERR]:      at com.thevoxelbox.voxelsniper.VoxelSniper.onInit(VoxelSniper.java:146)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameInitializationEventListener_Vox
elSniper_onInit36.handle(Unknown Source)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener
.java:95)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:305)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:320)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:324)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:201)
[17:31:39 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:140)
[17:31:39 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$z
ob000(SourceFile:1232)
[17:31:39 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:186)

[17:31:39 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:436)
[17:31:39 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)`

**Comment by Deamon5550** [comment]
I had thought that it was an issue with configurate , but try [Build 471](http://ci.voxelmodpack.com/job/VoxelSniper/471/) and see if it fixes the issue.

**Comment by seema84** [comment]
Build 471 works
