### ISSUE TITLE
1.12 incompatibility

### ISSUE THREAD

**Issue by DevonPalma** [TVPT/VoxelSniper#312]
The title pretty much says it all, Voxel sniper will not work for me nor my builders on any of our servers. Can we expect an update soon?

**Comment by Deamon5550** [comment]
what server software and versions, what errors appear?

**Comment by xwingevents** [comment]
`[19:54:20] [Server thread/ERROR]: Could not load 'plugins\VoxelSniper-8.5.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot-latest.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-latest.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot-latest.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-latest.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-latest.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml`

Latest build for Spigot 1.12 (spigot-1.12-R0.1-SNAPSHOT-b1319.jar)

**Comment by xwingevents** [comment]
Just realized Voxel is now for Sponge. Are they any compatible Spigot versions?

**Comment by Deamon5550** [comment]
yes on [bukkitdev](https://dev.bukkit.org/projects/voxelsniper)

**Comment by xwingevents** [comment]
Daemon, they work on 1.12?

**Comment by Deamon5550** [comment]
yes. VoxelSniper touches so little of the api that it works typically with no updates.
