### ISSUE TITLE
VoxelSniper-5.171.0-SNAPSHOT not work - Java 9 

### ISSUE THREAD

**Issue by andris155** [TVPT/VoxelSniper#315]
```
[14:03:23] [Server thread/ERROR]: Could not load 'plugins/VoxelSniper-5.171.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1233]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1233]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1233]
	... 6 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1233]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1233]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1233]
	... 6 more
```

**Comment by Deamon5550** [comment]
Can you test this build http://files.thevoxelbox.com/Plugins/VoxelSniper/VoxelSniper-5.172.0-SNAPSHOT.jar not sure why its breaking but the only place we use xml is loading the legacy configs that haven't been used for 6 years, probably safe to just remove.

**Comment by andris155** [comment]
Works perfectly. Thanks for fast update!!!
