### ISSUE TITLE
Error when trying to use VoxelSniper

### ISSUE THREAD

**Issue by Trimbell** [TVPT/VoxelSniper#321]
So, commands are working fine and I get an output in the chat. However, when I try to use the arrow or gunpowder to make changes, I get an error message in the console. Nothing appears in in game chat. This is the error:

```
[00:09:24 ERROR] [Sponge]: Could not pass InteractItemEvent$Secondary$MainHand$Impl to Plugin{id=voxelsniper, name=VoxelSniper, version=8.5.0-SNAPSHOT, description=Long range terrain editing, source=mods\VoxelSniper-8.5.0-SNAPSHOT.jar}
java.lang.NoSuchFieldError: ALL
        at com.thevoxelbox.voxelsniper.brush.PerformBrush.perform(PerformBrush.java:130) ~[PerformBrush.class:?]
        at com.thevoxelbox.voxelsniper.brush.PerformBrush.perform(PerformBrush.java:100) ~[PerformBrush.class:?]
        at com.thevoxelbox.voxelsniper.brush.shape.SnipeBrush.arrow(SnipeBrush.java:44) ~[SnipeBrush.class:?]
        at com.thevoxelbox.voxelsniper.brush.Brush.perform(Brush.java:71) ~[Brush.class:?]
        at com.thevoxelbox.voxelsniper.Sniper.snipe(Sniper.java:226) ~[Sniper.class:?]
        at com.thevoxelbox.voxelsniper.VoxelSniperListener.onPlayerInteract(VoxelSniperListener.java:48) ~[VoxelSniperListener.class:?]
        at org.spongepowered.common.event.listener.MainHandListener_VoxelSniperListener_onPlayerInteract35.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:371) [SpongeEventManager.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:388) [SpongeEventManager.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:197) [SpongeImpl.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractItemEventSecondary(SpongeCommonEventFactory.java:578) [SpongeCommonEventFactory.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:250) [PacketUtil.class:1.12.2-7.0.0-BETA-382]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:91) [PacketUtil.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjl000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-382]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zib000(SourceFile:4179) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by Deamon5550** [comment]
Needs updating for the latest sponge changes after https://github.com/SpongePowered/SpongeAPI/commit/ca87ec5818b6604d9c96da2af6e0fa70a9fb437a any build before that change will still work fine.

**Comment by zeronerve** [comment]
I'm getting a similar error when using a simple brush...what should i do?

```
[16:27:11 WARN]: java.io.EOFException: Stream ended prematurely
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:207)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:104)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:205)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:104)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.readFully(LZ4BlockInputStream.java:205)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:137)
[16:27:11 WARN]:        at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:89)
[16:27:11 WARN]:        at java.io.FilterInputStream.read(FilterInputStream.java:83)
[16:27:11 WARN]:        at com.boydti.fawe.object.changeset.FaweStreamChangeSet.readHeader(FaweStreamChangeSet.java:238)
[16:27:11 WARN]:        at com.boydti.fawe.object.changeset.DiskStorageHistory.getBlockIS(DiskStorageHistory.java:328)
[16:27:11 WARN]:        at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getBlockIterator(FaweStreamChangeSet.java:408)
[16:27:11 WARN]:        at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getIterator(FaweStreamChangeSet.java:685)
[16:27:11 WARN]:        at com.boydti.fawe.object.changeset.FaweStreamChangeSet.getIterator(FaweStreamChangeSet.java:522)
[16:27:11 WARN]:        at com.sk89q.worldedit.function.operation.ChangeSetExecutor.<init>(ChangeSetExecutor.java:59)
[16:27:11 WARN]:        at com.sk89q.worldedit.function.operation.ChangeSetExecutor.create(ChangeSetExecutor.java:90)
[16:27:11 WARN]:        at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1308)
[16:27:11 WARN]:        at com.sk89q.worldedit.LocalSession.undo(LocalSession.java:528)
[16:27:11 WARN]:        at com.thevoxelbox.voxelsniper.Sniper$3.run(Sniper.java:469)
[16:27:11 WARN]:        at com.boydti.fawe.object.FawePlayer$2.run(FawePlayer.java:232)
[16:27:11 WARN]:        at com.boydti.fawe.object.FawePlayer.queueAction(FawePlayer.java:260)
[16:27:11 WARN]:        at com.boydti.fawe.object.FawePlayer.runAction(FawePlayer.java:307)
[16:27:11 WARN]:        at com.thevoxelbox.voxelsniper.Sniper.undo(Sniper.java:464)
[16:27:11 WARN]:        at com.thevoxelbox.voxelsniper.command.VoxelUndoCommand.onCommand(VoxelUndoCommand.java:27)
[16:27:11 WARN]:        at com.thevoxelbox.voxelsniper.VoxelSniperListener.onCommand(VoxelSniperListener.java:76)
[16:27:11 WARN]:        at com.thevoxelbox.voxelsniper.VoxelSniper.onCommand(VoxelSniper.java:138)
[16:27:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:27:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:27:11 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[16:27:11 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:27:11 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:27:11 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:27:11 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Deamon5550** [comment]
@zeronerve Thats is a completely different error, on a different server platform, running a different version of voxelsniper, and its not even a bug in voxelsniper, its from fastasyncworldedit.

**Comment by zeronerve** [comment]
Thanks for pointing that out. Since it happened while trying voxel /u, and since voxel is mentioned in the log, and since I need help, I thought i'd ask for some help.
