### ISSUE TITLE
Error when starting server with VoxelSniper (Both the 8.3.0 and 8.4.0 from Ore)

### ISSUE THREAD

**Issue by MrDiamond123** [TVPT/VoxelSniper#332]
When running the plugin it doesn't load (but server still starts) with this in the logs
```
[16:09:09 ERROR] [Sponge]: Could not pass GameInitializationEvent$Impl to Plugin{id=voxelsniper, name=VoxelSniper, version=8.3.0, description=Long range terrain editing, source=mods\VoxelSniper-8.3.0.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
        at com.thevoxelbox.voxelsniper.VoxelSniper.onInit(VoxelSniper.java:145) ~[VoxelSniper.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_VoxelSniper_onInit10.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.2]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:426) ~[SpongeEventManager.class:1.12.2-7.1.2]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:471) ~[SpongeEventManager.class:1.12.2-7.1.2]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:248) ~[SpongeImpl.class:1.12.2-7.1.2]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:256) ~[SpongeImpl.class:1.12.2-7.1.2]
        at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:147) ~[SpongeVanilla.class:1.12.2-7.1.2]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$bbp000(SourceFile:1243) ~[nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.NamedCause
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        ... 12 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        ... 12 more
```

**Comment by gabizou** [comment]
Use 8.5.0-SNAPSHOT. 8.4.0 and older are not compatible with API 7.

**Comment by MrDiamond123** [comment]
you should put that file on ore (and thanks for that fast response)
