### ISSUE TITLE
VoxelSniper does not load normally from the server

### ISSUE THREAD

**Issue by doch2** [TVPT/VoxelSniper#362]
The voxel does not load normally from the 1.12.2 Minecraft server.

The operating system used Ubuntu 18.04 LTS, and Java 1.8 version.

The bucket used is CatServer, a power generation version of Spigot.

Error Message:
[21:29:13] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/VoxelSniper-5.172.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[JavaPluginLoader.class:git-CatServer-1.12.2-74f53eb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-74f53eb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-74f53eb]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-74f53eb]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:342) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:58) ~[JavaPlugin.class:git-CatServer-1.12.2-74f53eb]
	at com.thevoxelbox.voxelsniper.VoxelSniper.<init>(VoxelSniper.java:25) ~[VoxelSniper.class:5.171.0-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_252]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[PluginClassLoader.class:git-CatServer-1.12.2-74f53eb]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-74f53eb]
	... 7 more

**Comment by gabizou** [comment]
VoxelSniper doesn't support CatServer.
