### ISSUE TITLE
Erode Brush Internal Error (UraniumMC, V5.170.0)

### ISSUE THREAD

**Issue by KAMKEEL** [TVPT/VoxelSniper#365]
[17:16:40 INFO]: Kam issued server command: **/b e**

Expected behavior:
The brush should switch to erode brush. The same occurs with variants of /b e fill, /b e melt, /b e smooth

Experienced behavior:
An internal error occurs and will not switch the brush. However, switching to other brushes like/b t, /b b, /b bb, /b s, /b l. All of those work as planned. Only the erode brush seems to error.

Additional Information:
UraniumMC: 1710-stable-5-B20-afb7250-server (ALL VERSIONS THIS ERROR OCCURS)
Minecraft Forge: 1.7.10 - 10.13.4.1614
VoxelSniper: VoxelSniper-5.170.0-SNAPSHOT
DOES NOT OCCUR ON: **CAULDRON, KCAULDRON, THERMOS**

`> [17:16:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'b' in plugin VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:722) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1165) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:995) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:459) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.VerifyError: (class: com/thevoxelbox/voxelsniper/libs/com/martiansoftware/jsap/JSAP, method: class$ signature: (Ljava/lang/String;)Ljava/lang/Class;) Illegal type in constant pool
at com.thevoxelbox.voxelsniper.brush.ErodeBrush.<init>(ErodeBrush.java:37) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_262]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_262]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_262]
at com.thevoxelbox.voxelsniper.Sniper$SniperTool.instanciateBrush(Sniper.java:578) ~[?:?]
at com.thevoxelbox.voxelsniper.Sniper$SniperTool.setCurrentBrush(Sniper.java:544) ~[?:?]
at com.thevoxelbox.voxelsniper.Sniper.setBrush(Sniper.java:303) ~[?:?]
at com.thevoxelbox.voxelsniper.command.VoxelBrushCommand.onCommand(VoxelBrushCommand.java:63) ~[?:?]
at com.thevoxelbox.voxelsniper.VoxelSniperListener.onCommand(VoxelSniperListener.java:76) ~[?:?]
at com.thevoxelbox.voxelsniper.VoxelSniper.onCommand(VoxelSniper.java:138) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
... 13 more`

**Comment by gabizou** [comment]
The constant pool likely got transformed by whatever custom CraftBukkit extended implementation you're using that remaps what it supposes are NMS class mappings when they're not (VoxelSniper-legacy has its own parser that uses `/b e` and the string constants are being modified outside of VoxelSniper's awareness). Seeing as this code has not changed in years and previously has been known to work, I'd bet that the custom CraftBukkit implementation is at fault here for doing some transformational remapping of its own.
